# Generated by Django 5.1.7 on 2025-04-08 16:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid1, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
